from  selenium import webdriver
import time
class rich:
    def __init__(self):
        self.driver=webdriver.Chrome("/home/student/Downloads/chromedriver")
    def log(self):
        self.driver.get("https://rrsso.onelogin.com/login")
        self.driver.find_element_by_xpath("//*[@id='user_email']").send_keys("qatest@richrelevance.com")
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[@id='user_password']").send_keys("abcD1234!")
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[@id='user_submit']").click()
        time.sleep(7)
        self.driver.find_element_by_xpath("//*[@id='get-extension-container']/p[2]/button").click()
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='apps-view-container']/div[2]/div/div/div/div/div[1]/a").click()
        time.sleep(5)
        self.driver.switch_to_window(self.driver.window_handles[1])
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[@id='select2-chosen-1']").click()
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[@id='s2id_autogen1_search']").send_keys("Carters")
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='select2-results-1']/li[1]").click()
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[@id='navigationItems']/li[3]/a").click()
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[@id='rulesNavItem']/li[4]").click() 
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[@id='searchFilter']").send_keys("qa_test")
        time.sleep(3)
        k=self.driver.find_element_by_xpath("//*[@id='selectAll']")
        if(k):
            k.click()
            time.sleep(3)
            self.driver.find_element_by_xpath("//*[@id='deleteSelected']").click()
            time.sleep(3)
            self.driver.switch_to.alert.accept()
            time.sleep(3)
        self.driver.find_element_by_xpath("//*[@id='addRule']").click()
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='ruleName']").send_keys("qa_test")
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='noEndDate']").click()
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='categorySelector_filter']/div/div").click()
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='s2id_autogen18']").click()
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='s2id_autogen19_search']").send_keys("carter")
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='select2-result-label-43']").click()

        #self.driver.find_element_by_xpath("//*[@id='s2id_autogen23_search']").send_keys("carters")
        time.sleep(5)
        #self.driver.find_element_by_xpath("//*[@id='select2-result-label-43']").click()
        #time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='modal_from_view1438']/div/div/div[3]/button").click()
        time.sleep(5)
        self.driver.find_element_by_xpath("//*[@id='saveRule']").click()
rich=rich()
rich.log()
                
